"""create initial schema

Revision ID: ad488aab5d08
Revises: 19b432bf5f98
Create Date: 2026-03-29 21:25:04.812078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad488aab5d08'
down_revision: Union[str, Sequence[str], None] = '19b432bf5f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_connection_status', sa.String(length=20), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target')
    )
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_table('cpe_dictionary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpe_uri', sa.String(length=512), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpe_dictionary_cpe_uri'), 'cpe_dictionary', ['cpe_uri'], unique=True)
    op.create_index(op.f('ix_cpe_dictionary_product'), 'cpe_dictionary', ['product'], unique=False)
    op.create_index(op.f('ix_cpe_dictionary_vendor'), 'cpe_dictionary', ['vendor'], unique=False)
    op.create_table('feed_metadata',
    sa.Column('feed_name', sa.String(length=64), nullable=False),
    sa.Column('last_sync_time', sa.DateTime(), nullable=True),
    sa.Column('last_modified_start', sa.DateTime(), nullable=True),
    sa.Column('last_modified_end', sa.DateTime(), nullable=True),
    sa.Column('last_processed_cve', sa.String(length=64), nullable=True),
    sa.Column('total_cves', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('feed_name')
    )
    op.create_table('vulnerability_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_catalog_cve_id'), 'vulnerability_catalog', ['cve_id'], unique=True)
    op.create_table('cpe_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=64), nullable=False),
    sa.Column('cpe_uri', sa.String(length=512), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('version_start', sa.String(length=255), nullable=True),
    sa.Column('version_start_including', sa.Boolean(), nullable=True),
    sa.Column('version_end', sa.String(length=255), nullable=True),
    sa.Column('version_end_including', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['vulnerability_catalog.cve_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpe_entries_cpe_uri'), 'cpe_entries', ['cpe_uri'], unique=False)
    op.create_index(op.f('ix_cpe_entries_cve_id'), 'cpe_entries', ['cve_id'], unique=False)
    op.create_index(op.f('ix_cpe_entries_product'), 'cpe_entries', ['product'], unique=False)
    op.create_index(op.f('ix_cpe_entries_vendor'), 'cpe_entries', ['vendor'], unique=False)
    op.create_table('cvss_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=64), nullable=False),
    sa.Column('cvss_version', sa.String(length=16), nullable=False),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('vector', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['vulnerability_catalog.cve_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cvss_scores_cve_id'), 'cvss_scores', ['cve_id'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['cve_id'], ['vulnerability_catalog.cve_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_cve_id'), 'references', ['cve_id'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('scanner_type', sa.String(length=50), nullable=False),
    sa.Column('scan_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_scan_jobs_progress_range'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_jobs_asset_id'), 'scan_jobs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('severity_counts', sa.JSON(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_created_at', 'reports', ['created_at'], unique=False)
    op.create_index('ix_report_scan_job_id', 'reports', ['scan_job_id'], unique=False)
    op.create_index('ix_report_total_vuls', 'reports', ['total_vulnerabilities'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('scanner', sa.String(length=50), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_scan_job_id'), 'scan_results', ['scan_job_id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('cve', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('affected_ports', sa.JSON(), nullable=False),
    sa.Column('affected_services', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vulnerability_asset_id', 'vulnerabilities', ['asset_id'], unique=False)
    op.create_index('ix_vulnerability_created_at', 'vulnerabilities', ['created_at'], unique=False)
    op.create_index('ix_vulnerability_cve', 'vulnerabilities', ['cve'], unique=False)
    op.create_index('ix_vulnerability_cve_asset', 'vulnerabilities', ['cve', 'asset_id'], unique=False)
    op.create_index('ix_vulnerability_report_id', 'vulnerabilities', ['report_id'], unique=False)
    op.create_index('ix_vulnerability_severity', 'vulnerabilities', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vulnerability_severity', table_name='vulnerabilities')
    op.drop_index('ix_vulnerability_report_id', table_name='vulnerabilities')
    op.drop_index('ix_vulnerability_cve_asset', table_name='vulnerabilities')
    op.drop_index('ix_vulnerability_cve', table_name='vulnerabilities')
    op.drop_index('ix_vulnerability_created_at', table_name='vulnerabilities')
    op.drop_index('ix_vulnerability_asset_id', table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_scan_results_scan_job_id'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index('ix_report_total_vuls', table_name='reports')
    op.drop_index('ix_report_scan_job_id', table_name='reports')
    op.drop_index('ix_report_created_at', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_asset_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_references_cve_id'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_cvss_scores_cve_id'), table_name='cvss_scores')
    op.drop_table('cvss_scores')
    op.drop_index(op.f('ix_cpe_entries_vendor'), table_name='cpe_entries')
    op.drop_index(op.f('ix_cpe_entries_product'), table_name='cpe_entries')
    op.drop_index(op.f('ix_cpe_entries_cve_id'), table_name='cpe_entries')
    op.drop_index(op.f('ix_cpe_entries_cpe_uri'), table_name='cpe_entries')
    op.drop_table('cpe_entries')
    op.drop_index(op.f('ix_vulnerability_catalog_cve_id'), table_name='vulnerability_catalog')
    op.drop_table('vulnerability_catalog')
    op.drop_table('feed_metadata')
    op.drop_index(op.f('ix_cpe_dictionary_vendor'), table_name='cpe_dictionary')
    op.drop_index(op.f('ix_cpe_dictionary_product'), table_name='cpe_dictionary')
    op.drop_index(op.f('ix_cpe_dictionary_cpe_uri'), table_name='cpe_dictionary')
    op.drop_table('cpe_dictionary')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
